In [1]:
import numpy as np

# Исходные данные
x1 = np.array([1, 2, 3])
x2 = np.array([0, 1, 2])
y = np.array([2, 4, 7])

# Матрица признаков X
X = np.column_stack([np.ones(3), x1, x2])
print("Матрица X:")
print(X)

# Проверим линейную зависимость
print(f"\nПроверка линейной зависимости:")
print(f"x2 = {x2}")
print(f"x1 - 1 = {x1 - 1}")
print(f"Равны ли x2 и x1-1? {np.array_equal(x2, x1 - 1)}")

# Так как есть линейная зависимость, используем псевдообратную матрицу
print("\n" + "="*50)
print("РЕШЕНИЕ С ИСПОЛЬЗОВАНИЕМ ПСЕВДООБРАТНОЙ МАТРИЦЫ:")
print("="*50)

# Вычисляем коэффициенты через псевдообратную матрицу
beta = np.linalg.pinv(X) @ y
print(f"Коэффициенты: β0 = {beta[0]:.6f}, β1 = {beta[1]:.6f}, β2 = {beta[2]:.6f}")

# Проверяем подгонку для всех точек
print("\nПроверка подгонки:")
for i in range(3):
    y_pred = beta[0] + beta[1]*x1[i] + beta[2]*x2[i]
    print(f"x1={x1[i]}, x2={x2[i]}: y={y[i]}, ŷ={y_pred:.6f}")

# Проверка для требуемой точки x1=2, x2=1
print("\n" + "="*50)
print("ПРОВЕРКА ДЛЯ x1=2, x2=1:")
print("="*50)

x1_test, x2_test = 2, 1
y_pred_test = beta[0] + beta[1]*x1_test + beta[2]*x2_test
print(f"x1={x1_test}, x2={x2_test}")
print(f"Предсказанное значение: ŷ = {y_pred_test:.6f}")
print(f"Фактическое значение из данных: y = 4")

# Альтернативное решение - убрать мультиколлинеарность
print("\n" + "="*50)
print("АЛЬТЕРНАТИВНОЕ РЕШЕНИЕ (без x2):")
print("="*50)

X_simple = np.column_stack([np.ones(3), x1])
beta_simple = np.linalg.inv(X_simple.T @ X_simple) @ X_simple.T @ y
print(f"Коэффициенты: α0 = {beta_simple[0]:.6f}, α1 = {beta_simple[1]:.6f}")

# Проверка для x1=2 (x2 автоматически = 1)
y_pred_simple = beta_simple[0] + beta_simple[1]*2
print(f"\nДля x1=2: ŷ = {y_pred_simple:.6f}")
print(f"Фактическое значение: y = 4")

# Демонстрация эквивалентности решений
print("\n" + "="*50)
print("ПРОВЕРКА ЭКВИВАЛЕНТНОСТИ:")
print("="*50)
print("В полной модели: β1 + β2 =", beta[1] + beta[2])
print("В простой модели: α1 =", beta_simple[1])
print("Разница:", abs((beta[1] + beta[2]) - beta_simple[1]))

Матрица X:
[[1. 1. 0.]
 [1. 2. 1.]
 [1. 3. 2.]]

Проверка линейной зависимости:
x2 = [0 1 2]
x1 - 1 = [0 1 2]
Равны ли x2 и x1-1? True

РЕШЕНИЕ С ИСПОЛЬЗОВАНИЕМ ПСЕВДООБРАТНОЙ МАТРИЦЫ:
Коэффициенты: β0 = 0.388889, β1 = 1.444444, β2 = 1.055556

Проверка подгонки:
x1=1, x2=0: y=2, ŷ=1.833333
x1=2, x2=1: y=4, ŷ=4.333333
x1=3, x2=2: y=7, ŷ=6.833333

ПРОВЕРКА ДЛЯ x1=2, x2=1:
x1=2, x2=1
Предсказанное значение: ŷ = 4.333333
Фактическое значение из данных: y = 4

АЛЬТЕРНАТИВНОЕ РЕШЕНИЕ (без x2):
Коэффициенты: α0 = -0.666667, α1 = 2.500000

Для x1=2: ŷ = 4.333333
Фактическое значение: y = 4

ПРОВЕРКА ЭКВИВАЛЕНТНОСТИ:
В полной модели: β1 + β2 = 2.5
В простой модели: α1 = 2.5
Разница: 0.0


In [4]:
import numpy as np

# Исходные данные
x1 = np.array([1, 2, 3])
x2 = np.array([0, 1, 2])
y = np.array([2, 4, 7])

X = np.column_stack([np.ones(3), x1, x2])

beta = np.linalg.pinv(X) @ y

print("Матрица B (вектор коэффициентов):")
print(f"β = [{beta[0]:.6f}, {beta[1]:.6f}, {beta[2]:.6f}]")
print(f"β0 = {beta[0]:.6f}")
print(f"β1 = {beta[1]:.6f}")
print(f"β2 = {beta[2]:.6f}")

Матрица B (вектор коэффициентов):
β = [0.388889, 1.444444, 1.055556]
β0 = 0.388889
β1 = 1.444444
β2 = 1.055556
